### PR TITLE
cors header implemented also for POST requests

### PR DESCRIPTION
**Pull request by mbrucki**
Now the client will send the following response headers, also for POST requests, but without claiming them.

Access-Control-Allow-Credentials
Access-Control-Allow-Headers
Access-Control-Allow-Methods
Access-Control-Allow-Origin

### CODE REVIEW

**Comment by mbrucki** [comment]
I created this change because I found that when sending a POST request from client side GTM to sGTM, the statuses for both preflight and POST are correct, but a browser shows an error:
Screenshot 2023-11-16 at 12 15 47

**Comment by sahava** [comment]
> I created this change because I found that when sending a POST request from client side GTM to sGTM, the statuses for both preflight and POST are correct, but a browser shows an error: Screenshot 2023-11-16 at 12 15 47

Hi,

Please share the exact use case you are working with – the changes you propose should not be required, because the preflight check is passed. It looks like your actual POST request isn't sent correctly or there's no client to claim it, for example. I am using the Preflight client successfully with custom POST requests using the existing client code.

A client doesn't actually do anything if it doesn't use claimRequest(), by the way. The client code is basically ignored in that case.

**Comment by mbrucki** [comment]
Hi! I'm testing sending events from client gtm with the following custom HTML tag:
Screenshot 2023-11-17 at 10 26 19

On the server-side I have a preflight client from your template with the following setup:
Screenshot 2023-11-17 at 10 27 59

And GA4 measurement protocol client to claim the request.

So the OPTIONS request is all right:

Screenshot 2023-11-17 at 10 30 56

While the POST despite having status 200, causes the mentioned error in the browser, because in the response there are no required headers:

Screenshot 2023-11-17 at 10 33 22


I applied the proposed changes on my sGTM and it seems working:

Screenshot 2023-11-17 at 10 35 00

Where am I mistaken? :)

**Comment by sahava** [comment]
> Where am I mistaken? :)

The problem isn't the Preflight request. It's doing **exactly** what it's supposed to. It's allowlisting the headers, methods, origins, and credentials of the actual request, the POST request.

The "problem" is the MP Client itself. It isn't designed to write CORS headers in its response. You need to either use a client that does set CORS headers, or you can load the "Response Headers" tag template from the gallery, which lets you add CORS headers to the response when the tag fires. 

If you send your request to the regular GA4 client (copy a GA4 payload from actual requests), you'll see that it doesn't have the CORS errors (assuming Preflight passes), because the GA4 client does set responses correctly.

Adding the CORS headers to the main request isn't the responsibility of the Preflight request. The client that claims the request needs to do the decoration either independently or with the help of a tag that sets the headers.

**Comment by mbrucki** [comment]
Yes, GA4 client sets responses correctly but I want to use a custom endpoint, without "collect" in the name.

So the Response Headers tag + MP GA4 client do the job indeed. Thank you for your time!

**Pull request closed without merging**
